vsphere_user = 
vsphere_password = 
vsphere_server = 

vsphere_datacenter = 
vsphere_datastore = 
vsphere_resource_pool = 
network_cards = []
vsphere_folder = 
vsphere_vm_template_name = 
vsphere_virtual_machine_k3s_worker_name = 
vsphere_virtual_machine_k3s_worker_count = 3
vsphere_virtual_machine_k3s_master_name = 
vsphere_virtual_machine_k3s_master_count = 3
cpu_count = 
memory_size = //Megabytes
cpu_hot_add_enabled = true
cpu_hot_remove_enabled = true
memory_hot_add_enabled = true
domain = 
virtual_machine_network_address = 
virtual_machine_k3s_master_ip_address_start = 
virtual_machine_k3s_worker_ip_address_start = 
ipv4_submask = 
vm_gateway = 
vm_dns = []